### ISSUE TITLE
how to add a possible failed case to the corpus?

### ISSUE THREAD

**Issue by jacob-keller** [mhagger/diff-slider-tools#2]
Hi,

I found an issue when using indentHeuristic in git on one of my repositories which is not public. How would be the best way to add some test data to show how this failed in one specific case? Should I simply create a repository that has some test data that highlights the failure?

**Comment by mhagger** [comment]
@jacob-keller: When you say "issue", do you mean a bug (i.e., crash or invalid output), or do you mean that it didn't choose the aesthetically most pleasing diff?

If a bug, then it would be better to submit the test case to the upstream Git mailing list, and please CC me.

If the latter, then the question is whether your case is an example of a class of cases where the indent heuristic give poor output (for example, because it is in a language that wasn't included in the original corpus), or whether it is more or less an isolated case.

If it's an example of a class of similar cases, then we would probably need enough examples to sway the heuristic parameters in a way that improves cases like yours, and try to do so without making other cases significantly worse.

If it's more or less an isolated case, then I'd be curious to see it. But the indent heuristic is just a pretty stupid heuristic, and it does get some diffs wrong (there are roughly 144 examples in the corpus already where the indent heuristic doesn't get the best diff). That's a fact of life, I'm afraid. But feel free to play around with the parameters or the algorithm to try to get it to do a better job.

**Comment by jacob-keller** [comment]
It's a case where it got a different solution than expected and the regular
diff looked OK.

It's something like

+#endif
+#ifdef blah
+Code
#endif

I think it's because indent prefers the short line first so that it catches
opening braces but this doesn't match the chunk as we think of it for ifdef
and endif.

It's probably a fairly isolated case though.

**Comment by mhagger** [comment]
> It's something like
> 
> ```
> +#endif
> +#ifdef blah
> +  Code
>   #endif
> ```

( :point_up_2: I had to guess at the indentation because it was lost somewhere between email and issue.)

Yes, C preprocessor directives often confuse the indent heuristic. Philosophically speaking, I think it is because preprocessor directives represent a second "block" structure in the source text, independent of the C syntactical blocks; on top of that, they are required to be outdented to the left column, so the indentation clues that the indent heuristic relies on are garbled.

There are many such examples in the corpus already, so I don't think it is necessary to add another one. Thanks for your feedback!
